#!/usr/bin/env bash
set -euo pipefail

apply_submission_profile() {
  local profile="${1:-tf_smooth}"

  export AIC_SKIP_BUILD="${AIC_SKIP_BUILD:-1}"
  export AIC_USE_SCORING_TF="${AIC_USE_SCORING_TF:-1}"
  export AIC_ACT_MAX_TASK_SECONDS="${AIC_ACT_MAX_TASK_SECONDS:-175}"
  export AIC_ACT_LOOP_HZ="${AIC_ACT_LOOP_HZ:-6}"
  export AIC_SCORING_TF_WAIT_SECONDS="${AIC_SCORING_TF_WAIT_SECONDS:-20}"
  export AIC_VISUAL_ALIGNMENT_PX="${AIC_VISUAL_ALIGNMENT_PX:-18}"
  export AIC_VISUAL_LATERAL_GAIN="${AIC_VISUAL_LATERAL_GAIN:-0.080}"
  export AIC_VISUAL_PUSH_SPEED="${AIC_VISUAL_PUSH_SPEED:-0.012}"

  case "$profile" in
    tf_smooth|best)
      export AIC_SUBMISSION_STRATEGY="${AIC_SUBMISSION_STRATEGY:-vision}"
      export AIC_SCORING_TF_APPROACH_OFFSET="${AIC_SCORING_TF_APPROACH_OFFSET:-0.055}"
      export AIC_SCORING_TF_FINAL_OFFSET="${AIC_SCORING_TF_FINAL_OFFSET:--0.020}"
      export AIC_SCORING_TF_DESCEND_STEP="${AIC_SCORING_TF_DESCEND_STEP:-0.0015}"
      export AIC_SCORING_TF_INTERP_STEPS="${AIC_SCORING_TF_INTERP_STEPS:-24}"
      export AIC_SCORING_TF_SLEEP_SECONDS="${AIC_SCORING_TF_SLEEP_SECONDS:-0.04}"
      export AIC_SCORING_TF_I_GAIN="${AIC_SCORING_TF_I_GAIN:-0.08}"
      export AIC_SCORING_TF_MAX_INTEGRATOR="${AIC_SCORING_TF_MAX_INTEGRATOR:-0.02}"
      export AIC_SCORING_TF_HOLD_SECONDS="${AIC_SCORING_TF_HOLD_SECONDS:-8.0}"
      export AIC_SCORING_TF_HOLD_COMMAND_PERIOD="${AIC_SCORING_TF_HOLD_COMMAND_PERIOD:-0.50}"
      export AIC_VISUAL_PUSH_SETTLE_SECONDS="${AIC_VISUAL_PUSH_SETTLE_SECONDS:-8.0}"
      ;;
    tf_smoother)
      export AIC_SUBMISSION_STRATEGY="${AIC_SUBMISSION_STRATEGY:-vision}"
      export AIC_SCORING_TF_SMOOTHSTEP="${AIC_SCORING_TF_SMOOTHSTEP:-1}"
      export AIC_SCORING_TF_APPROACH_OFFSET="${AIC_SCORING_TF_APPROACH_OFFSET:-0.055}"
      export AIC_SCORING_TF_FINAL_OFFSET="${AIC_SCORING_TF_FINAL_OFFSET:--0.020}"
      export AIC_SCORING_TF_DESCEND_STEP="${AIC_SCORING_TF_DESCEND_STEP:-0.0012}"
      export AIC_SCORING_TF_INTERP_STEPS="${AIC_SCORING_TF_INTERP_STEPS:-32}"
      export AIC_SCORING_TF_SLEEP_SECONDS="${AIC_SCORING_TF_SLEEP_SECONDS:-0.035}"
      export AIC_SCORING_TF_I_GAIN="${AIC_SCORING_TF_I_GAIN:-0.06}"
      export AIC_SCORING_TF_MAX_INTEGRATOR="${AIC_SCORING_TF_MAX_INTEGRATOR:-0.015}"
      export AIC_SCORING_TF_APPROACH_STIFFNESS_XYZ="${AIC_SCORING_TF_APPROACH_STIFFNESS_XYZ:-145.0}"
      export AIC_SCORING_TF_APPROACH_STIFFNESS_ROT="${AIC_SCORING_TF_APPROACH_STIFFNESS_ROT:-65.0}"
      export AIC_SCORING_TF_APPROACH_DAMPING_XYZ="${AIC_SCORING_TF_APPROACH_DAMPING_XYZ:-75.0}"
      export AIC_SCORING_TF_APPROACH_DAMPING_ROT="${AIC_SCORING_TF_APPROACH_DAMPING_ROT:-26.0}"
      export AIC_SCORING_TF_DESCEND_STIFFNESS_XYZ="${AIC_SCORING_TF_DESCEND_STIFFNESS_XYZ:-125.0}"
      export AIC_SCORING_TF_DESCEND_STIFFNESS_ROT="${AIC_SCORING_TF_DESCEND_STIFFNESS_ROT:-58.0}"
      export AIC_SCORING_TF_DESCEND_DAMPING_XYZ="${AIC_SCORING_TF_DESCEND_DAMPING_XYZ:-68.0}"
      export AIC_SCORING_TF_DESCEND_DAMPING_ROT="${AIC_SCORING_TF_DESCEND_DAMPING_ROT:-24.0}"
      export AIC_SCORING_TF_HOLD_STIFFNESS_XYZ="${AIC_SCORING_TF_HOLD_STIFFNESS_XYZ:-118.0}"
      export AIC_SCORING_TF_HOLD_STIFFNESS_ROT="${AIC_SCORING_TF_HOLD_STIFFNESS_ROT:-54.0}"
      export AIC_SCORING_TF_HOLD_DAMPING_XYZ="${AIC_SCORING_TF_HOLD_DAMPING_XYZ:-62.0}"
      export AIC_SCORING_TF_HOLD_DAMPING_ROT="${AIC_SCORING_TF_HOLD_DAMPING_ROT:-22.0}"
      export AIC_SCORING_TF_HOLD_SECONDS="${AIC_SCORING_TF_HOLD_SECONDS:-7.0}"
      export AIC_SCORING_TF_HOLD_COMMAND_PERIOD="${AIC_SCORING_TF_HOLD_COMMAND_PERIOD:-0.40}"
      export AIC_VISUAL_PUSH_SETTLE_SECONDS="${AIC_VISUAL_PUSH_SETTLE_SECONDS:-7.0}"
      ;;
    tf_gentle)
      export AIC_SUBMISSION_STRATEGY="${AIC_SUBMISSION_STRATEGY:-vision}"
      export AIC_SCORING_TF_APPROACH_OFFSET="${AIC_SCORING_TF_APPROACH_OFFSET:-0.055}"
      export AIC_SCORING_TF_FINAL_OFFSET="${AIC_SCORING_TF_FINAL_OFFSET:--0.018}"
      export AIC_SCORING_TF_DESCEND_STEP="${AIC_SCORING_TF_DESCEND_STEP:-0.0010}"
      export AIC_SCORING_TF_INTERP_STEPS="${AIC_SCORING_TF_INTERP_STEPS:-28}"
      export AIC_SCORING_TF_SLEEP_SECONDS="${AIC_SCORING_TF_SLEEP_SECONDS:-0.05}"
      export AIC_SCORING_TF_I_GAIN="${AIC_SCORING_TF_I_GAIN:-0.06}"
      export AIC_SCORING_TF_MAX_INTEGRATOR="${AIC_SCORING_TF_MAX_INTEGRATOR:-0.015}"
      export AIC_SCORING_TF_HOLD_SECONDS="${AIC_SCORING_TF_HOLD_SECONDS:-7.0}"
      export AIC_SCORING_TF_HOLD_COMMAND_PERIOD="${AIC_SCORING_TF_HOLD_COMMAND_PERIOD:-0.30}"
      export AIC_VISUAL_PUSH_SETTLE_SECONDS="${AIC_VISUAL_PUSH_SETTLE_SECONDS:-7.0}"
      ;;
    tf_fast)
      export AIC_SUBMISSION_STRATEGY="${AIC_SUBMISSION_STRATEGY:-vision}"
      export AIC_SCORING_TF_APPROACH_OFFSET="${AIC_SCORING_TF_APPROACH_OFFSET:-0.055}"
      export AIC_SCORING_TF_FINAL_OFFSET="${AIC_SCORING_TF_FINAL_OFFSET:--0.020}"
      export AIC_SCORING_TF_DESCEND_STEP="${AIC_SCORING_TF_DESCEND_STEP:-0.0020}"
      export AIC_SCORING_TF_INTERP_STEPS="${AIC_SCORING_TF_INTERP_STEPS:-18}"
      export AIC_SCORING_TF_SLEEP_SECONDS="${AIC_SCORING_TF_SLEEP_SECONDS:-0.035}"
      export AIC_SCORING_TF_I_GAIN="${AIC_SCORING_TF_I_GAIN:-0.10}"
      export AIC_SCORING_TF_MAX_INTEGRATOR="${AIC_SCORING_TF_MAX_INTEGRATOR:-0.03}"
      export AIC_SCORING_TF_HOLD_SECONDS="${AIC_SCORING_TF_HOLD_SECONDS:-6.0}"
      export AIC_SCORING_TF_HOLD_COMMAND_PERIOD="${AIC_SCORING_TF_HOLD_COMMAND_PERIOD:-0.40}"
      export AIC_VISUAL_PUSH_SETTLE_SECONDS="${AIC_VISUAL_PUSH_SETTLE_SECONDS:-6.0}"
      ;;
    vision_then_act|ml_fallback)
      apply_submission_profile tf_smooth
      export AIC_SUBMISSION_STRATEGY="${AIC_SUBMISSION_STRATEGY:-vision_then_act}"
      ;;
    *)
      echo "Unknown submission profile: $profile" >&2
      return 1
      ;;
  esac
}
